# Generated by Django 4.1.7 on 2023-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_deadline',
            field=models.DateField(default=None),
        ),
    ]
