# Generated by Django 4.1.7 on 2023-03-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_deadline',
            field=models.DateField(blank=True, default=None),
        ),
    ]
