# Generated by Django 4.1.7 on 2023-03-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_imporant',
            new_name='task_important',
        ),
    ]
