# Generated by Django 4.1.7 on 2023-03-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_task_imporant_todo_task_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
