# Generated by Django 4.1.7 on 2023-03-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_slug',
            field=models.SlugField(blank=True),
        ),
    ]
