# Generated by Django 4.1.7 on 2023-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
