# Generated by Django 4.1.7 on 2023-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_expand',
            field=models.BooleanField(default=False),
        ),
    ]
