# Generated by Django 4.1.7 on 2023-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_todo_task_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_sorting',
            field=models.CharField(default='', max_length=20),
        ),
    ]
